In [1]:
import pandas as pd
import numpy as np

In [2]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
import time

In [ ]:
def EURKRW():
    df = pd.DataFrame(columns=["Date", "Close", "Open", "High", "Low", "유로환율_변동%_x"])
    
    options = webdriver.ChromeOptions()
    options.add_argument("--headless")
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-dev-shm-usage")
    service = Service()
    
    driver = webdriver.Chrome(service=service, options=options)
    url = "https://kr.investing.com/currencies/eur-krw-historical-data"
    driver.get(url)
    time.sleep(5)
    
    date_xpath = '//*[@id="__next"]/div[2]/div[2]/div[2]/div[1]/div[2]/div[3]/table/tbody/tr[1]/td[1]'
    close_xpath = '//*[@id="__next"]/div[2]/div[2]/div[2]/div[1]/div[2]/div[3]/table/tbody/tr[1]/td[2]'
    open_xpath = '//*[@id="__next"]/div[2]/div[2]/div[2]/div[1]/div[2]/div[3]/table/tbody/tr[1]/td[3]'
    high_xpath = '//*[@id="__next"]/div[2]/div[2]/div[2]/div[1]/div[2]/div[3]/table/tbody/tr[1]/td[4]'
    low_xpath = '//*[@id="__next"]/div[2]/div[2]/div[2]/div[1]/div[2]/div[3]/table/tbody/tr[1]/td[5]'
    volume_xpath = '//*[@id="__next"]/div[2]/div[2]/div[2]/div[1]/div[2]/div[3]/table/tbody/tr[1]/td[6]'
    change_xpath = '//*[@id="__next"]/div[2]/div[2]/div[2]/div[1]/div[2]/div[3]/table/tbody/tr[1]/td[7]'
    
    date = driver.find_element(By.XPATH, date_xpath).text
    close = driver.find_element(By.XPATH, close_xpath).text
    open_ = driver.find_element(By.XPATH, open_xpath).text
    high = driver.find_element(By.XPATH, high_xpath).text
    low = driver.find_element(By.XPATH, low_xpath).text
    volume = driver.find_element(By.XPATH, volume_xpath).text
    change = driver.find_element(By.XPATH, change_xpath).text
    
    def clean_number(text):
        return float(text.replace(',', '').replace('%', ''))
    
    from datetime import datetime
    date = datetime.strptime(date.replace('월', '-'), '%m- %d, %Y').date()
    
    new_row = {
        "Date": date,
        "Close": clean_number(close),
        "Open": clean_number(open_),
        "High": clean_number(high),
        "Low": clean_number(low),
        "유로환율_변동%_x": clean_number(change)
    }
    
    if date not in df["Date"].values:
        df = pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)
    
    df = df.sort_values("Date").reset_index(drop=True)
    
    driver.quit()
    return df

def DAX():
    df = pd.DataFrame(columns=["Date", "Dax_종가", "Dax_시가", "Dax_고가", "Dax_저가", "Dax_거래량(백 만)", "Dax_변동"])
    
    options = webdriver.ChromeOptions()
    options.add_argument("--headless")
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-dev-shm-usage")
    service = Service()
    
    driver = webdriver.Chrome(service=service, options=options)
    url = "https://kr.investing.com/indices/germany-30-historical-data"
    driver.get(url)
    time.sleep(5)
    
    date_xpath = '//*[@id="__next"]/div[2]/div[2]/div[2]/div[1]/div[2]/div[3]/table/tbody/tr[1]/td[1]'
    close_xpath = '//*[@id="__next"]/div[2]/div[2]/div[2]/div[1]/div[2]/div[3]/table/tbody/tr[1]/td[2]'
    open_xpath = '//*[@id="__next"]/div[2]/div[2]/div[2]/div[1]/div[2]/div[3]/table/tbody/tr[1]/td[3]'
    high_xpath = '//*[@id="__next"]/div[2]/div[2]/div[2]/div[1]/div[2]/div[3]/table/tbody/tr[1]/td[4]'
    low_xpath = '//*[@id="__next"]/div[2]/div[2]/div[2]/div[1]/div[2]/div[3]/table/tbody/tr[1]/td[5]'
    volume_xpath = '//*[@id="__next"]/div[2]/div[2]/div[2]/div[1]/div[2]/div[3]/table/tbody/tr[1]/td[6]'
    change_xpath = '//*[@id="__next"]/div[2]/div[2]/div[2]/div[1]/div[2]/div[3]/table/tbody/tr[1]/td[7]'
    
    date = driver.find_element(By.XPATH, date_xpath).text
    close = driver.find_element(By.XPATH, close_xpath).text
    open_ = driver.find_element(By.XPATH, open_xpath).text
    high = driver.find_element(By.XPATH, high_xpath).text
    low = driver.find_element(By.XPATH, low_xpath).text
    volume = driver.find_element(By.XPATH, volume_xpath).text
    change = driver.find_element(By.XPATH, change_xpath).text
    
    def clean_number(text):
        return float(text.replace(',', '').replace('M', '').replace('%', ''))
    
    from datetime import datetime
    date = datetime.strptime(date.replace('월', '-'), '%m- %d, %Y').date()
    
    new_row = {
        "Date": date,
        "Dax_종가": clean_number(close),
        "Dax_시가": clean_number(open_),
        "Dax_고가": clean_number(high),
        "Dax_저가": clean_number(low),
        "Dax_거래량(백 만)": clean_number(volume),
        "Dax_변동%": clean_number(change)
    }
    
    if date not in df["Date"].values:
        df = pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)
    
    df = df.sort_values("Date").reset_index(drop=True)
    
    driver.quit()
    return df

def VSTOXX():
    df = pd.DataFrame(columns=["Date", "VSTOXX_종가", "VSTOXX_시가", "VSTOXX_고가", "VSTOXX_저가", "VSTOXX_변동%"])
    
    options = webdriver.ChromeOptions()
    options.add_argument("--headless")
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-dev-shm-usage")
    service = Service()
    
    driver = webdriver.Chrome(service=service, options=options)
    url = "https://kr.investing.com/indices/stoxx-50-volatility-vstoxx-eur-historical-data"
    driver.get(url)
    time.sleep(5)
    
    date_xpath = '//*[@id="__next"]/div[2]/div[2]/div[2]/div[1]/div[2]/div[3]/table/tbody/tr[1]/td[1]'
    close_xpath = '//*[@id="__next"]/div[2]/div[2]/div[2]/div[1]/div[2]/div[3]/table/tbody/tr[1]/td[2]'
    open_xpath = '//*[@id="__next"]/div[2]/div[2]/div[2]/div[1]/div[2]/div[3]/table/tbody/tr[1]/td[3]'
    high_xpath = '//*[@id="__next"]/div[2]/div[2]/div[2]/div[1]/div[2]/div[3]/table/tbody/tr[1]/td[4]'
    low_xpath = '//*[@id="__next"]/div[2]/div[2]/div[2]/div[1]/div[2]/div[3]/table/tbody/tr[1]/td[5]'
    volume_xpath = '//*[@id="__next"]/div[2]/div[2]/div[2]/div[1]/div[2]/div[3]/table/tbody/tr[1]/td[6]'
    change_xpath = '//*[@id="__next"]/div[2]/div[2]/div[2]/div[1]/div[2]/div[3]/table/tbody/tr[1]/td[7]'
    
    date = driver.find_element(By.XPATH, date_xpath).text
    close = driver.find_element(By.XPATH, close_xpath).text
    open_ = driver.find_element(By.XPATH, open_xpath).text
    high = driver.find_element(By.XPATH, high_xpath).text
    low = driver.find_element(By.XPATH, low_xpath).text
    volume = driver.find_element(By.XPATH, volume_xpath).text
    change = driver.find_element(By.XPATH, change_xpath).text
    
    def clean_number(text):
        return float(text.replace(',', '').replace('M', '').replace('%', ''))
    
    from datetime import datetime
    date = datetime.strptime(date.replace('월', '-'), '%m- %d, %Y').date()
    
    new_row = {
        "Date": date,
        "VSTOXX_종가": clean_number(close),
        "VSTOXX_시가": clean_number(open_),
        "VSTOXX_고가": clean_number(high),
        "VSTOXX_저가": clean_number(low),
        "VSTOXX_변동%": clean_number(change)
    }
    
    if date not in df["Date"].values:
        df = pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)
    
    df = df.sort_values("Date").reset_index(drop=True)
    
    driver.quit()
    return df

def EUROSTOXX50():
    df = pd.DataFrame(columns=["Date", "EUROSTOXX50_종가", "EUROSTOXX50_시가", "EUROSTOXX50_고가", "EUROSTOXX50_저가", "EUROSTOXX50_변동%"])
    
    options = webdriver.ChromeOptions()
    options.add_argument("--headless")
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-dev-shm-usage")
    service = Service()
    
    driver = webdriver.Chrome(service=service, options=options)
    url = "https://kr.investing.com/indices/germany-30-historical-data"
    driver.get(url)
    time.sleep(5)
    
    date_xpath = '//*[@id="__next"]/div[2]/div[2]/div[2]/div[1]/div[2]/div[3]/table/tbody/tr[1]/td[1]'
    close_xpath = '//*[@id="__next"]/div[2]/div[2]/div[2]/div[1]/div[2]/div[3]/table/tbody/tr[1]/td[2]'
    open_xpath = '//*[@id="__next"]/div[2]/div[2]/div[2]/div[1]/div[2]/div[3]/table/tbody/tr[1]/td[3]'
    high_xpath = '//*[@id="__next"]/div[2]/div[2]/div[2]/div[1]/div[2]/div[3]/table/tbody/tr[1]/td[4]'
    low_xpath = '//*[@id="__next"]/div[2]/div[2]/div[2]/div[1]/div[2]/div[3]/table/tbody/tr[1]/td[5]'
    volume_xpath = '//*[@id="__next"]/div[2]/div[2]/div[2]/div[1]/div[2]/div[3]/table/tbody/tr[1]/td[6]'
    change_xpath = '//*[@id="__next"]/div[2]/div[2]/div[2]/div[1]/div[2]/div[3]/table/tbody/tr[1]/td[7]'
    
    date = driver.find_element(By.XPATH, date_xpath).text
    close = driver.find_element(By.XPATH, close_xpath).text
    open_ = driver.find_element(By.XPATH, open_xpath).text
    high = driver.find_element(By.XPATH, high_xpath).text
    low = driver.find_element(By.XPATH, low_xpath).text
    volume = driver.find_element(By.XPATH, volume_xpath).text
    change = driver.find_element(By.XPATH, change_xpath).text
    
    def clean_number(text):
        return float(text.replace(',', '').replace('M', '').replace('%', ''))
    
    from datetime import datetime
    date = datetime.strptime(date.replace('월', '-'), '%m- %d, %Y').date()
    
    new_row = {
        "Date": date,
        "EUROSTOXX50_종가": clean_number(close),
        "EUROSTOXX50_시가": clean_number(open_),
        "EUROSTOXX50_고가": clean_number(high),
        "EUROSTOXX50_저가": clean_number(low),
        "EUROSTOXX50_변동": clean_number(change)
    }
    
    if date not in df["Date"].values:
        df = pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)
    
    df = df.sort_values("Date").reset_index(drop=True)
    
    driver.quit()
    return df

In [17]:
EURKRW()

C:\Users\campus4D044\AppData\Local\Temp\ipykernel_10944\2181980226.py:47: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)

         Date   Close     Open     High      Low  유로환율_변동%_x
0  2025-07-28  1620.9  1624.82  1626.64  1620.53       -0.37

In [19]:
DAX()

C:\Users\campus4D044\AppData\Local\Temp\ipykernel_10944\3494221519.py:48: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)

,Date,Dax_종가,Dax_시가,Dax_고가,Dax_저가,Dax_거래량(백 만),Dax_변동,Dax_변동%
0,2025-07-25,24217.5,24097.33,24252.59,24065.19,54.01,NaN,-0.32

In [20]:
VSTOXX()

C:\Users\campus4D044\AppData\Local\Temp\ipykernel_10944\3675561032.py:47: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)

         Date  VSTOXX_종가  VSTOXX_시가  VSTOXX_고가  VSTOXX_저가  VSTOXX_변동%
0  2025-03-28       20.6      20.05      20.88      19.84        5.03

In [18]:
EUROSTOXX50()

C:\Users\campus4D044\AppData\Local\Temp\ipykernel_10944\3242182753.py:47: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)

,Date,EUROSTOXX50_종가,EUROSTOXX50_시가,EUROSTOXX50_고가,EUROSTOXX50_저가,EUROSTOXX50_변동%,EUROSTOXX50_변동
0,2025-07-25,24217.5,24097.33,24252.59,24065.19,NaN,-0.32

In [21]:
import pandas as pd
import time
from datetime import datetime
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service

class WebDataFetcher:
    def __init__(self):
        self.options = webdriver.ChromeOptions()
        self.options.add_argument("--headless")
        self.options.add_argument("--no-sandbox")
        self.options.add_argument("--disable-dev-shm-usage")
        self.service = Service()

    def _clean_number(self, text):
        return float(text.replace(',', '').replace('%', '').replace('M', ''))

    def _get_driver(self):
        return webdriver.Chrome(service=self.service, options=self.options)

    def _fetch_common(self, url):
        driver = self._get_driver()
        driver.get(url)
        time.sleep(5)

        get = lambda xpath: driver.find_element(By.XPATH, xpath).text
        try:
            date = get('//*[@id="__next"]/div[2]/div[2]/div[2]/div[1]/div[2]/div[3]/table/tbody/tr[1]/td[1]')
            close = get('//*[@id="__next"]/div[2]/div[2]/div[2]/div[1]/div[2]/div[3]/table/tbody/tr[1]/td[2]')
            open_ = get('//*[@id="__next"]/div[2]/div[2]/div[2]/div[1]/div[2]/div[3]/table/tbody/tr[1]/td[3]')
            high = get('//*[@id="__next"]/div[2]/div[2]/div[2]/div[1]/div[2]/div[3]/table/tbody/tr[1]/td[4]')
            low = get('//*[@id="__next"]/div[2]/div[2]/div[2]/div[1]/div[2]/div[3]/table/tbody/tr[1]/td[5]')
            volume = get('//*[@id="__next"]/div[2]/div[2]/div[2]/div[1]/div[2]/div[3]/table/tbody/tr[1]/td[6]')
            change = get('//*[@id="__next"]/div[2]/div[2]/div[2]/div[1]/div[2]/div[3]/table/tbody/tr[1]/td[7]')
        finally:
            driver.quit()

        date = datetime.strptime(date.replace("월", "-"), '%m- %d, %Y').date()
        return date, close, open_, high, low, volume, change

    def fetch_EURKRW(self):
        url = "https://kr.investing.com/currencies/eur-krw-historical-data"
        date, close, open_, high, low, _, change = self._fetch_common(url)
        return pd.DataFrame([{
            "Date": date,
            "Close": self._clean_number(close),
            "Open": self._clean_number(open_),
            "High": self._clean_number(high),
            "Low": self._clean_number(low),
            "유로환율_변동%_x": self._clean_number(change)
        }])

    def fetch_DAX(self):
        url = "https://kr.investing.com/indices/germany-30-historical-data"
        date, close, open_, high, low, volume, change = self._fetch_common(url)
        return pd.DataFrame([{
            "Date": date,
            "Dax_종가": self._clean_number(close),
            "Dax_시가": self._clean_number(open_),
            "Dax_고가": self._clean_number(high),
            "Dax_저가": self._clean_number(low),
            "Dax_거래량(백 만)": self._clean_number(volume),
            "Dax_변동%": self._clean_number(change)
        }])

    def fetch_VSTOXX(self):
        url = "https://kr.investing.com/indices/stoxx-50-volatility-vstoxx-eur-historical-data"
        date, close, open_, high, low, _, change = self._fetch_common(url)
        return pd.DataFrame([{
            "Date": date,
            "VSTOXX_종가": self._clean_number(close),
            "VSTOXX_시가": self._clean_number(open_),
            "VSTOXX_고가": self._clean_number(high),
            "VSTOXX_저가": self._clean_number(low),
            "VSTOXX_변동%": self._clean_number(change)
        }])

    def fetch_EUROSTOXX50(self):
        url = "https://kr.investing.com/indices/eu-stoxx50-historical-data"
        date, close, open_, high, low, _, change = self._fetch_common(url)
        return pd.DataFrame([{
            "Date": date,
            "EUROSTOXX50_종가": self._clean_number(close),
            "EUROSTOXX50_시가": self._clean_number(open_),
            "EUROSTOXX50_고가": self._clean_number(high),
            "EUROSTOXX50_저가": self._clean_number(low),
            "EUROSTOXX50_변동%": self._clean_number(change)
        }])

In [ ]:
import pickle

fetcher = WebDataFetcher()

with open("web_data_fetcher.pkl", "wb") as f:
    pickle.dump(fetcher, f)

In [26]:

pd.merge(pd.merge(WebDataFetcher().fetch_EURKRW(),WebDataFetcher().fetch_EUROSTOXX50(),on='Date'),WebDataFetcher().fetch_DAX(),on='Date')

Empty DataFrame
Columns: [Date, Close, Open, High, Low, 유로환율_변동%_x, EUROSTOXX50_종가, EUROSTOXX50_시가, EUROSTOXX50_고가, EUROSTOXX50_저가, EUROSTOXX50_변동%, Dax_종가, Dax_시가, Dax_고가, Dax_저가, Dax_거래량(백 만), Dax_변동%]
Index: []

In [27]:
WebDataFetcher().fetch_EURKRW()

         Date    Close     Open     High      Low  유로환율_변동%_x
0  2025-07-28  1619.46  1624.82  1626.64  1619.37       -0.46

In [28]:
WebDataFetcher().fetch_EUROSTOXX50()

,Date,EUROSTOXX50_종가,EUROSTOXX50_시가,EUROSTOXX50_고가,EUROSTOXX50_저가,EUROSTOXX50_변동%
0,2025-07-25,5352.16,5342.66,5362.23,5317.54,-0.06

In [29]:
WebDataFetcher().fetch_DAX()

         Date   Dax_종가    Dax_시가    Dax_고가    Dax_저가  Dax_거래량(백 만)  Dax_변동%
0  2025-07-25  24217.5  24097.33  24252.59  24065.19         54.01    -0.32

In [30]:
WebDataFetcher().fetch_VSTOXX()

         Date  VSTOXX_종가  VSTOXX_시가  VSTOXX_고가  VSTOXX_저가  VSTOXX_변동%
0  2025-03-28       20.6      20.05      20.88      19.84        5.03

In [31]:
import yfinance as yf
import pandas as pd

# 티커 목록
tickers = {
    "DAX": "^GDAXI",
    "EUROSTOXX50": "^STOXX50E",
    "CAC40": "^FCHI",
    "KRW_per_EUR": "EURKRW=X"
}

# 데이터프레임들을 저장할 리스트
df_list = []

for name, symbol in tickers.items():
    ticker = yf.Ticker(symbol)
    hist = ticker.history(period="2d", interval="1d")  # 전일 종가 포함해서 2일치
    if len(hist) >= 2:
        hist = hist.copy()
        hist = hist.tail(1)  # 오늘자 1일만 사용
        hist = hist[["Open", "High", "Low", "Close", "Volume"]]
        hist.columns = [f"{name}_{col}" for col in hist.columns]  # 컬럼 이름 변경
        hist["Date"] = hist.index.date
        hist.reset_index(drop=True, inplace=True)
        df_list.append(hist)
    else:
        print(f"{name} 데이터 부족")

# 여러 데이터프레임을 날짜 기준으로 병합
df_merged = df_list[0]
for df in df_list[1:]:
    df_merged = pd.merge(df_merged, df, on="Date", how="outer")

# 변동량 추가
for name in tickers.keys():
    close_col = f"{name}_Close"
    prev_day = yf.Ticker(tickers[name]).history(period="2d", interval="1d")
    if len(prev_day) == 2:
        change = prev_day["Close"].iloc[-1] - prev_day["Close"].iloc[-2]
        df_merged[f"{name}_Change"] = change

In [32]:
list(df_merged)

['DAX_Open',
 'DAX_High',
 'DAX_Low',
 'DAX_Close',
 'DAX_Volume',
 'Date',
 'EUROSTOXX50_Open',
 'EUROSTOXX50_High',
 'EUROSTOXX50_Low',
 'EUROSTOXX50_Close',
 'EUROSTOXX50_Volume',
 'CAC40_Open',
 'CAC40_High',
 'CAC40_Low',
 'CAC40_Close',
 'CAC40_Volume',
 'KRW_per_EUR_Open',
 'KRW_per_EUR_High',
 'KRW_per_EUR_Low',
 'KRW_per_EUR_Close',
 'KRW_per_EUR_Volume',
 'DAX_Change',
 'EUROSTOXX50_Change',
 'CAC40_Change',
 'KRW_per_EUR_Change']

In [34]:
import yfinance as yf
import pandas as pd

# 티커 목록
tickers = {
    "DAX": "^GDAXI",
    "EUROSTOXX50": "^STOXX50E",
    "CAC40": "^FCHI",
    "KRW_per_EUR": "EURKRW=X"
}

# 데이터프레임들을 저장할 리스트
df_list = []

for name, symbol in tickers.items():
    ticker = yf.Ticker(symbol)
    hist = ticker.history(period="2d", interval="1d")  # 전일 종가 포함해서 2일치
    if len(hist) >= 2:
        hist = hist.copy()
        hist = hist.tail(1)  # 오늘자 1일만 사용
        hist = hist[["Open", "High", "Low", "Close", "Volume"]]
        hist.columns = [f"{name}_{col}" for col in hist.columns]  # 컬럼 이름 변경
        hist["Date"] = hist.index.date
        hist.reset_index(drop=True, inplace=True)
        df_list.append(hist)
    else:
        print(f"{name} 데이터 부족")

# 여러 데이터프레임을 날짜 기준으로 병합
df_merged = df_list[0]
for df in df_list[1:]:
    df_merged = pd.merge(df_merged, df, on="Date", how="outer")

# 변동량 추가
for name in tickers.keys():
    close_col = f"{name}_Close"
    prev_day = yf.Ticker(tickers[name]).history(period="2d", interval="1d")
    if len(prev_day) == 2:
        change = prev_day["Close"].iloc[-1] - prev_day["Close"].iloc[-2]
        df_merged[f"{name}_Change"] = change

In [35]:
df_merged

,DAX_Open,DAX_High,DAX_Low,DAX_Close,DAX_Volume,Date,EUROSTOXX50_Open,EUROSTOXX50_High,EUROSTOXX50_Low,EUROSTOXX50_Close,...,CAC40_Volume,KRW_per_EUR_Open,KRW_per_EUR_High,KRW_per_EUR_Low,KRW_per_EUR_Close,KRW_per_EUR_Volume,DAX_Change,EUROSTOXX50_Change,CAC40_Change,KRW_per_EUR_Change
0,24097.330078,24252.589844,24065.189453,24217.5,54010400.0,2025-07-25,5342.660156,5362.22998,5317.540039,5352.160156,...,59054700.0,NaN,NaN,NaN,NaN,NaN,-78.429688,-3.040039,16.300293,6.450073
1,NaN,NaN,NaN,NaN,NaN,2025-07-28,NaN,NaN,NaN,NaN,...,NaN,1626.300049,1627.099976,1617.5,1618.800049,0.0,-78.429688,-3.040039,16.300293,6.450073

In [38]:
import yfinance as yf
import pandas as pd

# 유럽 주요 지수만
tickers = {
    "DAX": "^GDAXI",
    "EUROSTOXX50": "^STOXX50E",
    "CAC40": "^FCHI"
}

df_list = []

# 20일치 데이터 수집
for name, symbol in tickers.items():
    ticker = yf.Ticker(symbol)
    hist = ticker.history(period="21d", interval="1d")  # 오늘 포함 20일 확보

    if len(hist) >= 2:
        hist = hist.copy()
        hist = hist[["Open", "High", "Low", "Close", "Volume"]]
        hist.columns = [f"{name}_{col}" for col in hist.columns]
        hist["Date"] = hist.index.date
        hist.reset_index(drop=True, inplace=True)
        df_list.append(hist)
    else:
        print(f"{name} 데이터 부족")

# 병합
df_merged = df_list[0]
for df in df_list[1:]:
    df_merged = pd.merge(df_merged, df, on="Date", how="outer")

# 정렬
df_merged = df_merged.sort_values("Date").reset_index(drop=True)

# 각 종목별 변동량 계산
for name in tickers.keys():
    close_col = f"{name}_Close"
    change_col = f"{name}_Change"
    if close_col in df_merged.columns:
        df_merged[change_col] = df_merged[close_col].diff()

print("유럽 지수 데이터")
print(df_merged.tail())

유럽 지수 데이터
        DAX_Open      DAX_High       DAX_Low     DAX_Close  DAX_Volume  \
15  24309.390625  24335.259766  24191.630859  24307.800781    42777100
16  24236.089844  24237.410156  23921.830078  24041.900391    49151300
17  24246.800781  24310.960938  24122.189453  24240.820312    80487800
18  24502.990234  24514.929688  24235.439453  24295.929688    78043300
19  24097.330078  24252.589844  24065.189453  24217.500000           0

          Date  EUROSTOXX50_Open  EUROSTOXX50_High  EUROSTOXX50_Low  \
15  2025-07-21       5358.189941       5360.049805      5318.529785
16  2025-07-22       5332.319824       5332.319824      5277.850098
17  2025-07-23       5305.589844       5371.350098      5305.589844
18  2025-07-24       5365.919922       5396.310059      5337.970215
19  2025-07-25          0.000000          0.000000         0.000000

    EUROSTOXX50_Close  EUROSTOXX50_Volume   CAC40_Open   CAC40_High  \
15        5342.979980            18353100  7825.729980  7838.609863
16        5290.479980            16474700  7775.040039  7782.660156
17        5344.250000            33305200  7839.709961  7869.959961
18        5355.200195            26211600  7873.500000  7898.029785
19        5352.160156                   0     0.000000     0.000000

      CAC40_Low  CAC40_Close  CAC40_Volume  DAX_Change  EUROSTOXX50_Change  \
15  7757.680176  7798.220215      47487000   18.291016          -16.250000
16  7726.740234  7744.410156      47029700 -265.900391          -52.500000
17  7816.270020  7850.430176      66792400  198.919922           53.770020
18  7797.279785  7818.279785      74863300   55.109375           10.950195
19     0.000000  7834.580078             0  -78.429688           -3.040039

    CAC40_Change
15    -24.449707
16    -53.810059
17    106.020020
18    -32.150391
19     16.300293

In [63]:
symbol = "EURKRW=X"
ticker = yf.Ticker(symbol)
hist = ticker.history(period="603d", interval="1d")

hist = hist.copy()
hist = hist[["Open", "High", "Low", "Close"]]
hist.columns = [f"KRW_per_EUR_{col}" for col in hist.columns]
hist["Date"] = hist.index.date
hist.reset_index(drop=True, inplace=True)
# 변동량 계산
hist["KRW_per_EUR_Change"] = hist["KRW_per_EUR_Close"].diff()

hist['Date']=pd.to_datetime(hist['Date'],format='%Y-%m-%d')
hist.columns=['유로환율_종가','유로환율_시가','유로환율_고가','유로환율_저가','Date','유로환율_변동%_x']

hist=hist.reindex(columns=['Date','유로환율_종가','유로환율_시가','유로환율_고가','유로환율_저가','유로환율_변동%_x'])

In [64]:
hist

          Date      유로환율_종가      유로환율_시가      유로환율_고가      유로환율_저가  유로환율_변동%_x
0   2023-04-06  1434.369995  1439.109985  1431.930054  1433.130005         NaN
1   2023-04-07  1438.910034  1439.229980  1408.800049  1438.910034    5.780029
2   2023-04-10  1439.119995  1439.119995  1433.000000  1439.119995    0.209961
3   2023-04-11  1439.069946  1443.349976  1435.369995  1439.069946   -0.050049
4   2023-04-12  1439.699951  1456.180054  1439.579956  1439.699951    0.630005
..         ...          ...          ...          ...          ...         ...
595 2025-07-22  1615.359985  1623.520020  1610.000000  1615.589966   -0.180054
596 2025-07-23  1619.920044  1620.609985  1610.579956  1620.390015    4.800049
597 2025-07-24  1616.579956  1616.630005  1606.050049  1617.300049   -3.089966
598 2025-07-25  1611.739990  1622.280029  1609.939941  1612.349976   -4.950073
599 2025-07-28  1626.300049  1627.099976  1617.000000  1617.000000    4.650024

[600 rows x 6 columns]